### ISSUE TITLE
registered outlines are flipped horizontally when added and rescaled to raw data

### ISSUE THREAD

**Issue by stephenlenzi** [adamltyson/napari-cellfinder#11]
Hi I am having issues visualising registration atlas outlines on top of raw data when following the instructions in the docs.
I have tested this in a conda environment with a fresh installation of cellfinder 0.4.8 with pyside2 version 5.14 (had to downgrade for an unrelated issue).

To reproduce:

- open napari in commandline
- drag directory containing raw data into napari window
- drag registration folder into napari

the resulting outlines map on to the raw data but appear to be flipped horizontally relative to the raw data

**Comment by adamltyson** [comment]
I can't seem to replicate this. To ensure a problem would show up, I picked a brain that was mounted in an different orientation. I installed cellfinder from scratch, along with napari and the plugin, and all looks fine (albeit dodgy registration):
![Screenshot from 2021-01-12 16-37-01](https://user-images.githubusercontent.com/13147259/104344031-8bd9eb00-54f4-11eb-873f-01ffc3cabfa2.png)

**Comment by adamltyson** [comment]
Issue due to outdated BrainGlobe atlas. Closing.
