### ISSUE TITLE
[Feature] Allow tiff export of modified planes/images to individual tiff files

### ISSUE THREAD

**Issue by rdbcasillas** [adamltyson/napari-cellfinder#9]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to export different planes (napari folks would call these "time points"?) as individual tiff files. Following is a snapshot that captures the image/plane 131 (out of 549 total after loading cellfinder output folder):

![image](https://user-images.githubusercontent.com/9725334/96777335-d6454300-13af-11eb-805f-b27e372141ef.png)

When I modify this particular image, I don't see any way to export this particular modified image (or plane or time point). I can only export all images as a single TIFF at the moment

**Describe the solution you'd like**
After modifying a particular plane (by changing point size or color of selected points), I would love to export that modified image/plane as a tiff (or some other image format). 

Ideally, I would like to keep scrolling left to right, stop at an interesting location, modify that location and in the end export all the 549 images (some of which were modified) as individual tiffs. A functionality to only export all modified images would also work great. 

Thank you!

**Comment by adamltyson** [comment]
Hi @rdbcasillas,

This plugin only loads data into napari, and doesn't add any additional functionality. I think this is more likely to be a napari issue, would you be able to chat to them? This issue isn't specific to cellfinder, and I think the functionality could be useful to lots of napari users.

Thanks!

**Comment by adamltyson** [comment]
Closing this, as it's a napari issue.
